//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCVFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class listado
    {
        public int id_listado { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public Nullable<int> evento_id_evento { get; set; }
        public Nullable<int> ubicacion_id_mesa { get; set; }
        public string presente { get; set; }
    
        public virtual evento evento { get; set; }
        public virtual ubicacion ubicacion { get; set; }
    }
}
